apiVersion: v1
kind: Service
metadata:
  name: rnd-webapp
  namespace: stage
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/System/GetSystemHealth"
  labels:
    ASPNETCORE_ENVIRONMENT: stage
spec:
  ports:
  - name: http
    port: 12001 # 서비스가 생성할 포트
    targetPort: 12001 # 서비스가 접근할 pod의 포트
    nodePort: 32002
  selector:
    app: rnd-webapp
