apiVersion: v1
kind: Service
metadata:
  name: rnd-webapp
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/System/GetSystemHealth"
  labels:
    ASPNETCORE_ENVIRONMENT: dev
spec:
  selector:
    app: rnd-webapp
