apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rnd-webapp-hpa
  namespace: rnd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rnd-webapp
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
