apiVersion: v1
kind: Service
metadata:
  name: rnd-webapp
  namespace: prod
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/System/GetSystemHealth"
  labels:
    ASPNETCORE_ENVIRONMENT: stage
spec:
  selector:
    app: rnd-webapp
