apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rnd-webapp-hpa
  namespace: prod
spec:
  minReplicas: 1
  maxReplicas: 1000
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
